swiftmailer:
    url: '%env(MAILER_URL)%'
    transport: smtp
    host: smtp.gmail.com
    port: 587
    encryption: tls
    auth_mode: login
    username: hamza.bourguiga@esprit.tn
    password: FuckUPeople
    spool: { type: 'memory' }
