### test http request
POST http://127.0.0.1:8000/mobile/app HTTP/1.1
content-type: application/json 

{

}
### ADD USER API
POST http://127.0.0.1:8000/mobile/app/user HTTP/1.1
content-type: application/json 

{
    "name": "ddddd",
    "email": "sdfsdyyjuerwersdfjuf@sdfsdfsdfdssd.com",
    "role": "ROLE_USER",
    "image":"placeholder.jpg",
    "password": "123456"

}

### DELETE user API
POST http://127.0.0.1:8000/mobile/app/user/delete HTTP/1.1
content-type: application/json 

{
    "id": 24

}